version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: expense-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: expense-db
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: expense
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: